Modernize and rewrite plugin to support ZIP64
brianm/really-executable-jars-maven-plugin pull request #21
Opened 2022-11-25 10:45 UTC by wendigo

This change update Maven APIs to the newest version and introduces usage of Apache Commons Compress to support jars in ZIP64 format. Previous plugin version had a hard limit of 64K entries in the executable jar. After this change, limit for entries is 2^64-1 files which should be enough for most of the cases.

2022-11-25 10:46 UTC, wendigo commented
@brianm I was asked by @martint to create this PR, rather than used forked plugin. Let me know if you are able to accept this change and release a new version

2022-12-07 17:15 UTC, martint commented on pom.xml
> -    <profiles>
Why was this removed?

2022-12-07 17:15 UTC, martint commented on pom.xml
> -            <plugin>
Why was this removed?

2022-12-07 17:15 UTC, martint commented on src/main/java/org/skife/waffles/ReallyExecutableJarMojo.java
>   */
Unrelated change?

2022-12-07 17:15 UTC, martint commented on pom.xml
> +            </plugin>
How is this related?

2022-12-07 18:23 UTC, wendigo commented on src/main/java/org/skife/waffles/ReallyExecutableJarMojo.java
>   */
Updated maven parent checks for the license header.

2022-12-07 18:24 UTC, hgschmie requested changes
I am happy to review this PR but right now, there are too many unrelated changes to the build system/style changes etc. to allow a meaningful review.

2022-12-07 18:24 UTC, hgschmie commented on pom.xml
> +        <artifactId>maven-plugins</artifactId>
why would you change this?

2022-12-07 18:24 UTC, hgschmie commented on pom.xml
> +                                    <maxJdkVersion>1.9</maxJdkVersion>
this is not necessary / jdk enforcement is enough (and part of the basepom)

2022-12-07 18:24 UTC, wendigo commented on pom.xml
> -            <plugin>
Updated maven parent.

2022-12-07 18:25 UTC, wendigo commented on pom.xml
> +        <artifactId>maven-plugins</artifactId>
To pull in the newest maven plugin dependencies.

2022-12-07 18:25 UTC, wendigo commented on src/main/java/org/skife/waffles/ReallyExecutableJarMojo.java
> +@Mojo( name = "really-executable-jar",
Most of the maven plugins are formatted that way. I prefer to keep it consistent.

2022-12-07 18:34 UTC, martint commented on pom.xml
> -    <profiles>
Maybe so, but it should be a separate change

2022-12-07 18:34 UTC, martint commented on pom.xml
> -            <plugin>
Is that related to adding support for ZIP64 or just opportunistic? If the latter, it should be a separate change.

2022-12-07 18:36 UTC, martint commented on src/main/java/org/skife/waffles/ReallyExecutableJarMojo.java
> +@Mojo( name = "really-executable-jar",
But this is not part of the Apache Maven project, so it doesn't need to follow its formatting rules. The code should be formatted according to this project's choice.

2022-12-07 18:36 UTC, hgschmie commented on src/main/java/org/skife/waffles/ReallyExecutableJarMojo.java
> +            throw new UncheckedIOException( e );
this is not necessary, the mojo code allows for mojoexecutionexception, no need to throw a runtime exception

2022-12-07 18:36 UTC, hgschmie commented on pom.xml
> -            <plugin>
this project uses the basepom parent (https://basepom.org/). Feel free to upgrade to the latest version.

2022-12-07 18:36 UTC, hgschmie commented on src/main/java/org/skife/waffles/ReallyExecutableJarMojo.java
> +@Mojo( name = "really-executable-jar",
You are contributing to an outside project, and I would suggest that you adhere to the style that the project you want to contribute is using. Otherwise, you may face a hard time getting your changes in. :-)

2022-12-07 18:44 UTC, wendigo commented
@hgschmie & @martint I've dropped all the modernization changes and left only switch to apache commons compress to produce valid ZIP64 executable jar.

2022-12-07 18:55 UTC, hgschmie reviewed
please upgrade to 2.0.0-SNAPSHOT and review the suggested changes if you feel that they work for you. Afterwards I am good to merge and release.

2022-12-07 18:55 UTC, hgschmie commented on src/main/java/org/skife/waffles/ReallyExecutableJarMojo.java
> +            jar.setUseZip64(Zip64Mode.AsNeeded);
consider using `AlwaysWithCompatibility`. While there are not a lot of folks left that use Java < 8, it may make a difference to them.

2022-12-07 18:55 UTC, hgschmie commented on pom.xml
> +    <version>1.5.0-SNAPSHOT</version>
as we drop java 7 compat (java 8 required), this should be 2.0.0

2022-12-07 18:55 UTC, hgschmie commented on src/main/java/org/skife/waffles/ReallyExecutableJarMojo.java
> +                jar.finish();
I found this confusing. Shouldn't that be closer to the closing of the outer try (ZipArchiveOutputStream jar ...) { } block? 

Also I wonder if there is not a subtle bug lurking as neither finish nor close flush the output stream. Have a `jar.flush();` in there as well?

2022-12-08 17:55 UTC, hgschmie approved these changes

2022-12-08 17:55 UTC, merged